language: node_js
sudo: false
node_js:
  - 12
  - 11
before_install: "npm install -g codecov istanbul"
install: "npm ci"
script: "npm run test"
after_sucess: "istanbul cover ./node_modules/@hapi/lab/bin/lab  && codecov"