language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/lab/bin/lab --report lcovonly  -- -l  && codecov
  - codecov